# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    ################################
    # Run Linter against code base #
    ################################
    - name: Lint Code Base
      uses: docker://github/super-linter:v3
      env:
        VALIDATE_ALL_CODEBASE: true
        
    
    #############################################
    # Validate Presentations Meet Specification #
    #############################################    
    - name: Glasswall Rebuild
      uses: tpilvelis-gw/rebuild-action@v1
      with:
        filetype: 'pptx'

    ################################
    # Run Static Analyser          #
    ################################
        
    ################################
    # Run Unit Tests               #
    ################################
  
    ################################
    # Run Integration Tests        #
    ################################
  
    ################################
    # Build Project                #
    ################################
